from pathlib import Path

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#073b3a">
<title>Erik Yeghinyan | Banking & Financial Operations</title><meta name="description" content="Outcome-focused portfolio covering banking, customer service, call center operations, AML/BSA and fraud prevention.">
<style>
:root{--forest:#073b3a;--deep:#062a2b;--cream:#f5f1e8;--paper:#fbfaf6;--ink:#132c2d;--muted:#637475;--line:#d9ddd5;--mint:#a8e6cf;--aqua:#41c7b5;--orange:#ff7548;--white:#fff}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--cream);color:var(--ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;line-height:1.55}a{color:inherit;text-decoration:none}.wrap{width:min(1240px,calc(100% - 56px));margin:auto}
.nav{height:76px;background:var(--paper);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20}.nav .wrap{height:100%;display:flex;align-items:center;justify-content:space-between}.name{font-size:.9rem;font-weight:900;letter-spacing:.08em}.name i{color:var(--orange);font-style:normal}.navlinks{display:flex;gap:26px;font-size:.68rem;font-weight:800;text-transform:uppercase;letter-spacing:.09em;color:#536869}.navlinks a:hover{color:var(--forest)}.hire{background:var(--forest);color:#fff!important;padding:11px 15px;border-radius:2px}
.hero{background:var(--paper);padding:78px 0 64px}.hero-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:70px;align-items:end}.eyebrow{display:flex;align-items:center;gap:10px;color:#4d6767;font-size:.67rem;font-weight:900;text-transform:uppercase;letter-spacing:.14em}.eyebrow:before{content:"";width:30px;height:3px;background:var(--orange)}h1{font-size:clamp(4.4rem,8.5vw,8.7rem);line-height:.78;letter-spacing:-.09em;margin:35px 0 34px}.outline{display:block;color:transparent;-webkit-text-stroke:2px var(--forest)}.roleline{display:flex;gap:8px;flex-wrap:wrap}.roleline span{padding:9px 12px;background:#e7eee8;border-radius:3px;font-size:.7rem;font-weight:800;color:#264a49}.intro-panel{border-left:1px solid #bdc9c2;padding-left:42px}.intro-panel h2{font-size:1.75rem;letter-spacing:-.04em;line-height:1.13;margin:0 0 20px}.intro-panel p{color:var(--muted);margin:0}.intro-actions{display:flex;gap:10px;margin-top:28px}.button{padding:12px 15px;font-size:.74rem;font-weight:850;border:1px solid var(--forest)}.button.primary{background:var(--forest);color:#fff}.button.secondary{background:transparent}
.kpi-band{background:var(--forest);color:#fff;padding:0}.kpis{display:grid;grid-template-columns:repeat(6,1fr)}.kpi{min-height:154px;padding:28px 20px;border-left:1px solid rgba(255,255,255,.17);display:flex;flex-direction:column;justify-content:center}.kpi:last-child{border-right:1px solid rgba(255,255,255,.17)}.kpi strong{font-size:2.6rem;line-height:1;letter-spacing:-.07em;color:var(--mint)}.kpi span{font-size:.65rem;text-transform:uppercase;letter-spacing:.08em;color:#b9cfca;margin-top:12px}.kpi.hot strong{color:#ff9a78}
.section{padding:100px 0}.section-top{display:grid;grid-template-columns:210px 1fr;gap:50px;margin-bottom:50px}.section-id{font-size:.67rem;text-transform:uppercase;letter-spacing:.14em;font-weight:900;color:var(--orange);border-top:2px solid var(--orange);padding-top:13px}.section-top h2{font-size:clamp(2.5rem,5vw,5rem);line-height:.93;letter-spacing:-.065em;margin:0;max-width:850px}.section-top p{color:var(--muted);max-width:700px;margin:19px 0 0}
.who{background:#e8eee9}.who-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.who-card{background:var(--paper);padding:34px;border:1px solid #d1d9d2}.who-card:first-child{background:var(--deep);color:#fff;border:0}.who-card small{color:var(--orange);text-transform:uppercase;letter-spacing:.12em;font-size:.65rem;font-weight:900}.who-card h3{font-size:2rem;letter-spacing:-.05em;line-height:1.05;margin:38px 0 20px}.who-card p{color:#687b7b;margin:0}.who-card:first-child p{color:#a9c0bc}.value-list{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:30px}.value-list span{padding:12px;background:#e9efe9;font-size:.72rem;font-weight:800}.who-card:first-child .value-list span{background:#103f40;color:#cae0db}
.outcomes{background:var(--paper)}.case-list{display:grid;gap:20px}.case{border:1px solid var(--line);background:#fff}.case-header{display:grid;grid-template-columns:210px 1fr auto;align-items:center;gap:30px;padding:24px 28px;border-bottom:1px solid var(--line)}.company{font-size:.75rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em;color:var(--forest)}.case-header h3{margin:0;font-size:1.35rem}.case-header .date{font-size:.67rem;color:var(--muted)}.case-body{display:grid;grid-template-columns:repeat(3,1fr)}.case-col{padding:27px;min-height:215px;border-right:1px solid var(--line)}.case-col:last-child{border:0;background:#eef5ef}.case-col small{font-size:.62rem;color:#718181;text-transform:uppercase;letter-spacing:.12em;font-weight:900}.case-col h4{margin:20px 0 10px;font-size:.95rem}.case-col p{margin:0;color:var(--muted);font-size:.8rem}.outcome-value{font-size:2rem;line-height:1;letter-spacing:-.06em;color:var(--forest);font-weight:900;margin:20px 0 11px}.outcome-list{padding:0;margin:20px 0 0;list-style:none}.outcome-list li{font-size:.78rem;color:#365655;margin:8px 0;padding-left:13px;position:relative}.outcome-list li:before{content:"";position:absolute;left:0;top:.65em;width:5px;height:5px;background:var(--orange);border-radius:50%}
.risk{background:var(--deep);color:#fff}.risk .section-top h2{color:#fff}.risk .section-top p{color:#9db4b1}.risk-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.risk-card{min-height:210px;padding:25px;background:#0c393a;border:1px solid #265456}.risk-card b{display:block;color:var(--mint);font-size:.67rem}.risk-card h3{font-size:1rem;margin:37px 0 13px}.risk-card p{font-size:.76rem;color:#9db5b2;margin:0}.risk-card:nth-child(4n+2){border-top:3px solid var(--orange)}
.proof{background:#e8eee9}.proof-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.score{background:var(--orange);color:#fff;padding:36px;min-height:390px;display:flex;flex-direction:column}.score strong{font-size:6rem;line-height:.9;letter-spacing:-.09em}.score h3{font-size:1.5rem;margin:20px 0 8px}.score p{margin:0;color:#ffe0d5}.score-foot{margin-top:auto;border-top:1px solid rgba(255,255,255,.4);padding-top:18px;font-size:.7rem}.quotes{display:grid;grid-template-columns:1fr 1fr;gap:10px}.quote{background:#fff;padding:25px;border:1px solid var(--line);display:flex;flex-direction:column}.quote:before{content:"“";font-size:3rem;color:var(--aqua);line-height:.5}.quote p{font-size:.9rem;margin:22px 0}.quote footer{margin-top:auto;border-top:1px solid var(--line);padding-top:14px;display:flex;justify-content:space-between;color:var(--muted);font-size:.65rem}.quote footer b{color:var(--teal)}
.credentials{background:var(--paper)}.credential-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.credential{min-height:185px;padding:24px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.credential small{color:var(--orange);font-weight:900;text-transform:uppercase;letter-spacing:.1em}.credential h3{font-size:.95rem;line-height:1.4;margin:35px 0 0}.bottom-grid{display:grid;grid-template-columns:1fr 1fr;margin-top:22px;gap:12px}.bottom-card{background:#eef2ed;padding:28px}.bottom-card small{color:var(--teal);font-weight:900;text-transform:uppercase;letter-spacing:.1em}.bottom-card h3{margin:24px 0 7px;font-size:1.4rem}.bottom-card p{margin:0;color:var(--muted);font-size:.8rem}.language{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #d3dbd4;font-size:.78rem}.language span{color:var(--muted)}
.close{padding:75px 0;background:var(--forest);color:#fff}.close-grid{display:flex;align-items:end;justify-content:space-between;gap:40px}.close h2{font-size:clamp(2.8rem,5vw,5rem);line-height:.9;letter-spacing:-.06em;margin:0}.close h2 span{color:var(--mint)}.close a{padding:15px 18px;background:var(--orange);color:#fff;font-size:.75rem;font-weight:900}.footer{background:#041f20;color:#749694;padding:24px 0;font-size:.65rem}.footer .wrap{display:flex;justify-content:space-between}
@media(max-width:980px){.navlinks a:not(.hire){display:none}.hero-grid,.section-top{grid-template-columns:1fr}.intro-panel{border-left:0;border-top:1px solid #bdc9c2;padding:28px 0 0}.kpis{grid-template-columns:repeat(3,1fr)}.kpi:nth-child(3){border-right:1px solid rgba(255,255,255,.17)}.case-header{grid-template-columns:1fr}.case-body{grid-template-columns:1fr}.case-col{border-right:0;border-bottom:1px solid var(--line);min-height:auto}.risk-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.wrap{width:min(100% - 28px,1240px)}.hero{padding:58px 0 45px}h1{font-size:4.3rem}.kpis{grid-template-columns:1fr 1fr}.kpi{min-height:125px}.section{padding:72px 0}.who-grid,.proof-grid,.quotes,.credential-grid,.bottom-grid{grid-template-columns:1fr}.value-list,.risk-grid{grid-template-columns:1fr}.section-top{gap:22px}.case-header{padding:21px}.close-grid{display:block}.close a{display:inline-block;margin-top:28px}.footer .wrap{display:block;line-height:1.8}}

/* Dark premium fintech edition */
:root{--black:#05060a;--graphite:#0b0d14;--panel:#111522;--panel2:#171b2b;--white:#f8f9ff;--silver:#a7adc0;--stroke:#262b3b;--cobalt:#4f6bff;--violet:#8b5cf6;--ice:#7dd3fc}
body{background:var(--black);color:var(--white);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.wrap{width:min(1260px,calc(100% - 64px))}
.nav{height:74px;background:rgba(5,6,10,.86);border-bottom:1px solid rgba(255,255,255,.08);backdrop-filter:blur(20px)}.name{color:#fff}.name i{color:#7dd3fc}.navlinks{color:#a7adc0}.navlinks a:hover{color:#fff}.hire{background:#fff;color:#070810!important;border-radius:999px}
.hero{position:relative;overflow:hidden;background:radial-gradient(circle at 75% 15%,rgba(79,107,255,.27),transparent 30%),radial-gradient(circle at 20% 90%,rgba(139,92,246,.2),transparent 32%),#05060a;padding:105px 0 118px}.hero:after{content:"";position:absolute;right:-10vw;top:20px;width:42vw;height:42vw;border-radius:50%;border:1px solid rgba(125,211,252,.2);box-shadow:0 0 100px rgba(79,107,255,.12);pointer-events:none}.hero-grid{grid-template-columns:1.35fr .65fr;gap:80px;position:relative;z-index:1}.eyebrow{color:#aeb5ca}.eyebrow:before{background:linear-gradient(90deg,#4f6bff,#8b5cf6)}h1{font-size:clamp(5rem,10vw,10.5rem);color:#fff}.outline{background:linear-gradient(90deg,#7dd3fc,#8b5cf6);-webkit-background-clip:text;background-clip:text;color:transparent;-webkit-text-stroke:0}.roleline span{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.11);color:#d9dced;border-radius:999px;padding:9px 14px}.intro-panel{border-left-color:#34394a}.intro-panel h2{font-size:2rem;color:#fff}.intro-panel p{color:#a7adc0}.button{border-radius:999px;border-color:#444a5c}.button.primary{background:linear-gradient(90deg,#4f6bff,#6d5bf5);color:#fff;border:0}.button.secondary{color:#fff}
.kpi-band{position:relative;background:#080a10;padding:0 0 65px}.kpis{position:relative;margin-top:-48px;z-index:4;gap:10px}.kpi{min-height:165px;border:1px solid #262b3b!important;border-radius:18px;background:linear-gradient(145deg,rgba(25,30,47,.96),rgba(11,13,20,.98));padding:24px;box-shadow:0 24px 55px rgba(0,0,0,.3)}.kpi strong,.kpi.hot strong{color:#fff;font-size:2.8rem}.kpi:nth-child(3) strong,.kpi:nth-child(6) strong{background:linear-gradient(90deg,#7dd3fc,#8b5cf6);-webkit-background-clip:text;color:transparent}.kpi span{color:#8f96aa}
.section{padding:115px 0}.section-id{border:0;padding:0;color:#7dd3fc}.section-top h2{color:#fff}.section-top p{color:#9299ad}.who{background:#0b0d14}.who-card,.who-card:first-child{border:1px solid #262b3b;background:#111522;color:#fff;border-radius:22px;padding:38px}.who-card:first-child{background:linear-gradient(145deg,#19203a,#111522)}.who-card small{color:#7dd3fc}.who-card h3{font-size:2.15rem}.who-card p,.who-card:first-child p{color:#9da5ba}.value-list span,.who-card:first-child .value-list span{background:#1b2030;color:#d9dced;border:1px solid #2a3042;border-radius:9px}
.outcomes{background:#f6f7fb;color:#111827}.outcomes .section-top h2{color:#111827}.outcomes .section-top p{color:#667085}.outcomes .section-id{color:#4f6bff}.case-list{gap:16px}.case{border:0;border-radius:22px;overflow:hidden;background:#fff;box-shadow:0 18px 55px rgba(15,23,42,.08)}.case-header{border-color:#e5e7ef;padding:27px 31px}.company{color:#4f6bff}.case-body{background:#fff}.case-col{border-color:#e8eaf0;padding:30px}.case-col:last-child{background:linear-gradient(145deg,#eef1ff,#f7f5ff)}.case-col small{color:#7b8191}.case-col p{color:#667085}.outcome-value{color:#4f6bff;font-size:2.35rem}.outcome-list li{color:#495267}.outcome-list li:before{background:#8b5cf6}
.risk{background:#070810}.risk .section-top p{color:#9299ad}.risk-grid{gap:12px}.risk-card{background:#111522;border:1px solid #252a3a;border-radius:17px;min-height:220px}.risk-card:nth-child(4n+2){border-top:1px solid #252a3a}.risk-card:hover{transform:translateY(-4px);border-color:#4f6bff;transition:.2s}.risk-card b{color:#7dd3fc}.risk-card p{color:#9299ad}
.proof{background:#10131d}.proof .section-top h2{color:#fff}.proof .section-top p{color:#9299ad}.score{background:linear-gradient(145deg,#4f6bff,#7c3aed);border-radius:22px;min-height:410px}.score p{color:#e9e7ff}.quote{background:#171b27;border:1px solid #282d3e;border-radius:16px}.quote:before{color:#7dd3fc}.quote p{color:#f0f2fa}.quote footer{border-color:#303648;color:#8f96aa}.quote footer b{color:#7dd3fc}
.credentials{background:#f6f7fb;color:#111827}.credentials .section-top h2{color:#111827}.credentials .section-top p{color:#667085}.credentials .section-id{color:#4f6bff}.credential-grid{border:0;gap:11px}.credential{border:1px solid #e4e7ee!important;border-radius:16px;background:#fff;min-height:190px}.credential small{color:#4f6bff}.bottom-card{background:#e9ecf5;border-radius:16px}.bottom-card small{color:#4f6bff}.language{border-color:#d7dbe7}
.close{background:radial-gradient(circle at 75%,rgba(139,92,246,.28),transparent 27%),#06070b;padding:90px 0}.close h2{color:#fff}.close h2 span{background:linear-gradient(90deg,#7dd3fc,#8b5cf6);-webkit-background-clip:text;color:transparent}.close a{background:#fff;color:#070810;border-radius:999px;padding:15px 22px}.footer{background:#030407;color:#6f7587}
@media(max-width:980px){.kpis{margin-top:-35px}.hero-grid{grid-template-columns:1fr}.hero:after{opacity:.5}.case-header{grid-template-columns:1fr}.case-body{grid-template-columns:1fr}.risk-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.wrap{width:min(100% - 28px,1260px)}.hero{padding:75px 0 90px}h1{font-size:4.7rem}.kpi-band{padding-bottom:45px}.kpis{margin-top:-30px}.kpi{border-radius:13px}.who-grid,.proof-grid,.quotes,.credential-grid,.bottom-grid{grid-template-columns:1fr}.case,.who-card,.score{border-radius:15px}}
@media(prefers-reduced-motion:no-preference){.hero-grid>div{animation:rise .7s ease both}.intro-panel{animation:rise .7s .12s ease both}.kpi{animation:rise .55s ease both}.kpi:nth-child(2){animation-delay:.05s}.kpi:nth-child(3){animation-delay:.1s}.kpi:nth-child(4){animation-delay:.15s}.kpi:nth-child(5){animation-delay:.2s}.kpi:nth-child(6){animation-delay:.25s}@keyframes rise{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}}
</style></head><body>
<header class="nav"><div class="wrap"><a class="name" href="#top">ERIK YEGHINYAN<i>.</i></a><nav class="navlinks"><a href="#about">Who I Am</a><a href="#outcomes">Experience & Outcomes</a><a href="#risk">AML & Fraud</a><a href="#proof">Performance</a><a class="hire" href="mailto:eyeghinyane@gmail.com">Contact ↗</a></nav></div></header>
<main><section class="hero" id="top"><div class="wrap hero-grid"><div><div class="eyebrow">Banking · Customer Service · Call Center</div><h1>Erik<span class="outline">Yeghinyan</span></h1><div class="roleline"><span>Banking Operations</span><span>Customer Experience</span><span>AML/BSA</span><span>Fraud Prevention</span></div></div><aside class="intro-panel"><h2>I turn customer needs, transaction data and risk signals into clear action.</h2><p>10+ years of customer-service experience and 4+ years across banking, call-center, compliance and research operations.</p><div class="intro-actions"><a class="button primary" href="#outcomes">Review outcomes ↓</a><a class="button secondary" href="mailto:eyeghinyane@gmail.com">Contact me ↗</a></div></aside></div></section>
<section class="kpi-band" aria-label="Key performance indicators"><div class="wrap kpis"><div class="kpi"><strong>40+</strong><span>Daily banking transactions</span></div><div class="kpi"><strong>30+</strong><span>Daily AML reviews</span></div><div class="kpi"><strong>25%</strong><span>Review efficiency gain</span></div><div class="kpi hot"><strong>30%</strong><span>Fewer false-positive escalations</span></div><div class="kpi"><strong>100%</strong><span>Quality after probation</span></div><div class="kpi hot"><strong>10/10</strong><span>Detailed customer reports</span></div></div></section>
<section class="section who" id="about"><div class="wrap"><div class="section-top"><div class="section-id">01 · Who I am</div><div><h2>Customer judgment with operational discipline.</h2><p>My experience connects three areas financial institutions depend on: accurate transaction execution, responsive customer communication and risk-aware investigation.</p></div></div><div class="who-grid"><article class="who-card"><small>Professional focus</small><h3>Banking that feels human and operates with control.</h3><p>I bring frontline service and back-office investigation together—so customers receive clear help while the institution receives accurate records and responsible escalation.</p><div class="value-list"><span>Ownership</span><span>Accuracy</span><span>Risk awareness</span><span>Clear communication</span></div></article><article class="who-card"><small>Career coverage</small><h3>Branch, digital, phone and investigation channels.</h3><p>I have processed banking transactions, handled high-volume calls, supported customers by email and live chat, verified identities, reviewed AML alerts, researched fraud patterns and documented decisions.</p><div class="value-list"><span>In-person banking</span><span>Phone support</span><span>Email & live chat</span><span>Transaction monitoring</span></div></article></div></div></section>
<section class="section outcomes" id="outcomes"><div class="wrap"><div class="section-top"><div class="section-id">02 · Experience & outcomes</div><div><h2>Every role shows the work and what changed.</h2><p>Responsibilities are organized as operating context, action and outcome—not generic résumé statements.</p></div></div><div class="case-list">
<article class="case"><header class="case-header"><div class="company">Santander Bank</div><h3>Teller / Relationship Banker</h3><span class="date">Jun 2026—Present</span></header><div class="case-body"><div class="case-col"><small>Operating context</small><h4>High-volume branch service</h4><p>Customer transactions, cash handling, transfers, loan and mortgage payments, card payments and account questions.</p></div><div class="case-col"><small>Actions</small><h4>Controlled execution</h4><p>Process 40+ daily transactions; verify identity and details; complete CTR documentation and operational processing; recognize fraud indicators and escalate concerns.</p></div><div class="case-col"><small>Outcome</small><div class="outcome-value">10/10</div><p>Repeated perfect detailed customer reports for helpfulness, knowledge, speed, courtesy and needs resolution.</p></div></div></article>
<article class="case"><header class="case-header"><div class="company">Green Dot Bank</div><h3>AML Compliance Analyst</h3><span class="date">Sep 2024—Sep 2025</span></header><div class="case-body"><div class="case-col"><small>Operating context</small><h4>High-volume AML queue</h4><p>ACH, P2P, account takeover, unusual spending and fraud alerts reviewed in Unit21 using KYC and transaction evidence.</p></div><div class="case-col"><small>Actions</small><h4>New risk-review logic</h4><p>Identified recurring transaction trends, applied a clearer risk-based review approach, strengthened documentation and escalated only when evidence left material risk unresolved.</p></div><div class="case-col"><small>Outcome</small><div class="outcome-value">30% ↓</div><ul class="outcome-list"><li>False-positive escalations reduced 30%</li><li>Review efficiency increased 25%</li><li>Weekly target achieved with 100% quality after probation</li></ul></div></div></article>
<article class="case"><header class="case-header"><div class="company">IDBank</div><h3>Operational Compliance Support Specialist</h3><span class="date">Sep 2023—Sep 2024</span></header><div class="case-body"><div class="case-col"><small>Operating context</small><h4>Digital banking support</h4><p>Phone, email and live-chat service combined with onboarding, account access, AML/KYC checks and fraud review.</p></div><div class="case-col"><small>Actions</small><h4>Expanded identity verification</h4><p>Used video ID, document matching, OSINT and relevant social-media cross-checks to resolve identity discrepancies and detect suspicious onboarding signals.</p></div><div class="case-col"><small>Outcome</small><div class="outcome-value">360°</div><p>Created a more complete identity-review approach, improved confidence in onboarding decisions and supported faster routing of higher-risk cases.</p></div></div></article>
<article class="case"><header class="case-header"><div class="company">TP</div><h3>Multilingual Call-Center Representative & Interpreter</h3><span class="date">Sep 2023—Sep 2024</span></header><div class="case-body"><div class="case-col"><small>Operating context</small><h4>High-stakes inbound calls</h4><p>Healthcare, legal, government, administrative and customer-service conversations in Armenian, English and Russian.</p></div><div class="case-col"><small>Actions</small><h4>Accurate communication</h4><p>Verified callers, interpreted without changing meaning, documented outcomes, routed requests, de-escalated difficult calls and protected confidentiality.</p></div><div class="case-col"><small>Outcome</small><div class="outcome-value">3</div><p>Delivered consistent service across three languages while helping callers and organizations reach clear next steps in sensitive situations.</p></div></div></article>
<article class="case"><header class="case-header"><div class="company">DiplomaSafe</div><h3>Lead Research Specialist</h3><span class="date">Oct 2023—May 2024</span></header><div class="case-body"><div class="case-col"><small>Operating context</small><h4>Institutional account research</h4><p>Schools, universities, organizations, decision-makers and contact data used for qualified outreach.</p></div><div class="case-col"><small>Actions</small><h4>Verified research</h4><p>Cross-checked websites, public sources, professional platforms and Hunter; removed duplicates and corrected incomplete account records.</p></div><div class="case-col"><small>Outcome</small><div class="outcome-value">Clean data</div><p>Delivered verified institutional accounts and decision-maker research that made outreach more focused and usable.</p></div></div></article>
</div></div></section>
<section class="section risk" id="risk"><div class="wrap"><div class="section-top"><div class="section-id">03 · AML/BSA & fraud</div><div><h2>Financial-crime capabilities remain visible.</h2><p>Exact controls, typologies, investigation methods and reporting skills relevant to banking and fintech roles.</p></div></div><div class="risk-grid"><article class="risk-card"><b>01</b><h3>AML/BSA Investigations</h3><p>Transaction monitoring, alert triage, unusual activity review, risk-based disposition and escalation.</p></article><article class="risk-card"><b>02</b><h3>Fraud Prevention</h3><p>Account takeover, suspicious documents, identity discrepancies, unusual spending and fraud referral.</p></article><article class="risk-card"><b>03</b><h3>KYC & Due Diligence</h3><p>CIP, KYC, CDD, EDD, customer risk, video ID and document verification.</p></article><article class="risk-card"><b>04</b><h3>Payment Risk</h3><p>ACH, P2P, transfers, velocity, counterparties and transaction-pattern analysis.</p></article><article class="risk-card"><b>05</b><h3>Reporting & Controls</h3><p>CTR procedures, SAR narrative support, evidence-based decisions and audit-ready documentation.</p></article><article class="risk-card"><b>06</b><h3>Screening & Research</h3><p>OFAC awareness, sanctions controls, OSINT, adverse media and World-Check.</p></article><article class="risk-card"><b>07</b><h3>Case Management</h3><p>Unit21 investigations, chronological case notes, quality review and defensible closure rationale.</p></article><article class="risk-card"><b>08</b><h3>Customer Protection</h3><p>Identity controls, confidentiality, escalation, clear explanations and needs-focused resolution.</p></article></div></div></section>
<section class="section proof" id="proof"><div class="wrap"><div class="section-top"><div class="section-id">04 · Performance proof</div><div><h2>KPIs supported by customer feedback.</h2><p>Selected detailed reports all recorded perfect satisfaction and likelihood-to-recommend scores.</p></div></div><div class="proof-grid"><article class="score"><strong>100%</strong><h3>Selected-report satisfaction</h3><p>All supplied detailed reports: 10/10 satisfaction and 10/10 likelihood to recommend.</p><div class="score-foot">Verified customer-experience reports · August 2026</div></article><div class="quotes"><article class="quote"><p>Erik has been exceptional with his customer service.</p><footer><span>Aug 21</span><b>10/10</b></footer></article><article class="quote"><p>Extremely friendly and helpful with my transaction.</p><footer><span>Aug 20</span><b>10/10</b></footer></article><article class="quote"><p>Fast and speedy and very delightful attention.</p><footer><span>Aug 25</span><b>10/10</b></footer></article><article class="quote"><p>Great customer service. New guy is very nice!</p><footer><span>Aug 18</span><b>10/10</b></footer></article></div></div></div></section>
<section class="section credentials"><div class="wrap"><div class="section-top"><div class="section-id">05 · Credentials</div><div><h2>Learning, education and languages.</h2><p>Professional credentials remain separate from academic background.</p></div></div><div class="credential-grid"><article class="credential"><small>ACAMS</small><h3>Enhancing Financial Inclusion with a Risk-Based Approach</h3></article><article class="credential"><small>AML / KYC</small><h3>Foundations in Anti-Money Laundering and Know Your Customer</h3></article><article class="credential"><small>Banking</small><h3>Banking and Insurance: AML/KYC Compliance</h3></article><article class="credential"><small>Financial Crime</small><h3>Cryptocurrency Financial Crime & Compliance Bootcamp</h3></article><article class="credential"><small>PMI · 2025</small><h3>Leveraging AI for Governance, Risk and Compliance</h3></article><article class="credential"><small>Privacy</small><h3>GDPR and Data Privacy Training</h3></article></div><div class="bottom-grid"><article class="bottom-card"><small>Education</small><h3>B.A. Communication · GPA 3.8/4.0</h3><p>LCC International University · 2024</p></article><article class="bottom-card"><small>Languages</small><div style="margin-top:17px"><div class="language"><b>Armenian</b><span>Native</span></div><div class="language"><b>English</b><span>Advanced · C2</span></div><div class="language"><b>Russian</b><span>Advanced</span></div></div></article></div></div></section>
<section class="close"><div class="wrap close-grid"><h2>Service that earns trust.<br><span>Controls that protect it.</span></h2><a href="mailto:eyeghinyane@gmail.com">CONTACT ERIK ↗</a></div></section></main><footer class="footer"><div class="wrap"><span>ERIK YEGHINYAN © 2026</span><span>BANKING · CUSTOMER SERVICE · CALL CENTER · AML/BSA</span></div></footer>
</body></html>'''

def build() -> None:
    output = Path(__file__).with_name("index.html")
    output.write_text(HTML, encoding="utf-8")
    print(f"Built {output.name} with {len(HTML):,} characters")

if __name__ == "__main__":
    build()
